### ISSUE TITLE
你的电脑还在用吗

### ISSUE THREAD

**Issue by rathan520** [Hlynford/Lenovo-ThinkVision-M8500t-D303-Hackintosh#1]
2021年11月在咸鱼收了一台m8500t，更新引导至0.75，目前在用Monterey，并驱动了gt720，引导挺快，mono内置喇叭也可以正常使用，你的电脑还在吗？

**Comment by Hlynford** [comment]
挺久没折腾黑苹果了

**Comment by rathan520** [comment]
今年刚好从朋友那拆机了i5 4590 和六根内存条，加上自己还有一些闲置的sata固态，台式机苹果网卡等等，git上看到你的efi，248收了一台准系统，自己改了改efi轻松就装好系统了，感谢哟

**Comment by rathan520** [comment]
![C25CBDF4-2BB5-4C41-A595-B0306610F76D](https://user
![1284186F-FCAB-4223-8101-2F5C6E3C6D76](https://user-images.githubusercontent.com/44227759/145035089-59a36084-f809-490f-923e-b1b751c92849.jpeg)
-images.githubusercontent.com/44227759/145035070-11a5ba65-a8e5-4e07-b60d-600791327aaa.jpeg)
![0378DBEB-8C07-4366-BD50-6EB06FDF8F2F](https://user-images.githubusercontent.com/44227759/145035084-6d0a7129-345a-4120-a692-7f3a5398a50f.jpeg)

**Comment by rathan520** [comment]
![BECB95D2-76C6-4315-A2D9-4934F693CDAD](https://user-images.githubusercontent.com/44227759/145035159-85ea26b5-17b1-45b5-9279-a8b8635379c9.jpeg)
![3315C675-2FF3-4996-A5B4-FA820E008A28](https://user-images.githubusercontent.com/44227759/145035175-7f4b96cf-035a-47a6-ae78-8e58e3609a03.jpeg)
![5230455E-8DAD-4802-AB19-8BDADE7E6939](https://user-images.githubusercontent.com/44227759/145035179-ea34398e-da28-4519-88b0-39ee2a315628.jpeg)

**Comment by Hlynford** [comment]
这个EFI很完美哦，完成度应该算99%了，非常nice(๑•̀ㅂ•́)و✧

**Comment by rathan520** [comment]
很喜欢这个机箱的造型，办公用性能还是很不错的，没有你说启动久的问题，睡眠也很正常，我接了4k屏幕，完美黑苹果，等矿难显卡便宜了搞张A卡，这两年低价卖了460 584 和588，现在想买买不起了，哈哈哈哈

**Comment by rathan520** [comment]
另外没想到吧，一年没更新efi了，还是有人会用到，再次感谢哟

**Comment by Hlynford** [comment]
> 另外没想到吧，一年没更新efi了，还是有人会用到，再次感谢哟

启动慢可能是因为接dp双屏的问题，的确没想到还有用这机器玩黑苹果的小伙伴讷

**Comment by Hlynford** [comment]
> 我又回来啦，这太电脑真是好玩呢，配置换了一些，i5 4590 换了 E3 1231 V3，显卡GT720换了RX560 4G ，另外修改了bios支持nvme转接上了m.2 sn750 500G，同时修改bios解锁了cfg lock，加上我的台式机943602cs，相当赞的黑苹果主机，目前0.8.0已经在用Monterey 12.3了,机型imac pro 1,1。

**Comment by Hlynford** [comment]
这是基本上除了主板，基本都换了，厉害了
